version: '3.3'

networks:
  demo_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  web:
    image: ghcr.io/lhotakj/demo:latest
    container_name: web
    restart: unless-stopped
    networks:
      demo_network:
        ipv4_address: 172.28.1.1
    ports:
      - "5000:5000"
#    expose:
#      - 5000

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      demo_network:
        ipv4_address: 172.28.1.2

# docker-compose -f docker-compose.yaml up -d --build