name: "build, push ARM docker image and deploy on Oracle cloud"

run-name: "Build, push ARM docker image and deploy on Oracle cloud"

on: [ push ]

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v1"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: "Login to GitHub Package Registry"
        if: "contains(github.event.head_commit.message, 'push')"
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Build & Push Docker image"
        if: "contains(github.event.head_commit.message, 'push')"
        run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/demo:latest -f ./Dockerfile --push --platform=linux/arm64,linux/amd64 .

      - name: "Copy docker-compose on the Oracle host"
        if: "contains(github.event.head_commit.message, 'deploy')"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_TARGET }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          username: ubuntu
          port: 22
          overwrite: true
          source: "docker-compose.yaml,nginx"
          target: "/tmp/"

      - name: "Deployment to Oracle host"
        if: "contains(github.event.head_commit.message, 'deploy')"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_TARGET }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          username: ubuntu
          port: 22
          script: |
            cd /tmp
            echo :: Killing docker compose
            sudo docker-compose kill --remove-orphans
            echo :: Starting docker compose
            sudo docker-compose -f docker-compose.yaml up -d --build
