name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v1"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v1"
      - name: "Login to GitHub Package Registry"
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Build & Push Docker image"
        run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/myimage:${GITHUB_SHA} -f [path to Dockerfile] --push --platform=linux/arm64,linux/amd64 .
